In [ ]:
# Loading required file
import pandas as pd
df=pd.read_csv('/content/customer_churn_data.csv')
df

,CustomerID,Age,Gender,Tenure,MonthlyCharges,ContractType,InternetService,TotalCharges,TechSupport,Churn
0,1,49,Male,4,88.35,Month-to-Month,Fiber Optic,353.40,Yes,Yes
1,2,43,Male,0,36.67,Month-to-Month,Fiber Optic,0.00,Yes,Yes
2,3,51,Female,2,63.79,Month-to-Month,Fiber Optic,127.58,No,Yes
3,4,60,Female,8,102.34,One-Year,DSL,818.72,Yes,Yes
4,5,42,Male,32,69.01,Month-to-Month,NaN,2208.32,No,Yes
...,...,...,...,...,...,...,...,...,...,...
995,996,42,Male,41,37.14,Month-to-Month,Fiber Optic,1522.74,Yes,Yes
996,997,62,Male,9,80.93,Month-to-Month,NaN,728.37,No,Yes
997,998,51,Female,15,111.72,Month-to-Month,Fiber Optic,1675.80,Yes,Yes
998,999,39,Male,68,65.67,One-Year,NaN,4465.56,No,Yes
999,1000,50,Male,1,56.67,Month-to-Month,NaN,56.67,No,Yes

In [ ]:
# checking if dataset contains any null values and sum by each column
df.isnull().sum()

CustomerID           0
Age                  0
Gender               0
Tenure               0
MonthlyCharges       0
ContractType         0
InternetService    297
TotalCharges         0
TechSupport          0
Churn                0
dtype: int64

In [ ]:
# checking Unique values of the InternetServicecolumn
df.InternetService.unique()

array(['Fiber Optic', 'DSL', nan], dtype=object)

In [ ]:
a=df.InternetService=='Fiber Optic'
df[a]

,CustomerID,Age,Gender,Tenure,MonthlyCharges,ContractType,InternetService,TotalCharges,TechSupport,Churn
0,1,49,Male,4,88.35,Month-to-Month,Fiber Optic,353.40,Yes,Yes
1,2,43,Male,0,36.67,Month-to-Month,Fiber Optic,0.00,Yes,Yes
2,3,51,Female,2,63.79,Month-to-Month,Fiber Optic,127.58,No,Yes
8,9,40,Female,53,49.81,Two-Year,Fiber Optic,2639.93,Yes,No
9,10,50,Female,10,61.55,Month-to-Month,Fiber Optic,615.50,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...
989,990,45,Male,1,83.57,One-Year,Fiber Optic,83.57,Yes,Yes
991,992,24,Male,32,81.93,Month-to-Month,Fiber Optic,2621.76,Yes,Yes
993,994,38,Male,4,102.27,One-Year,Fiber Optic,409.08,No,Yes
995,996,42,Male,41,37.14,Month-to-Month,Fiber Optic,1522.74,Yes,Yes
997,998,51,Female,15,111.72,Month-to-Month,Fiber Optic,1675.80,Yes,Yes

In [ ]:
# filling missing values with empty instead of deleting for better results
df["InternetService"]=df['InternetService'].fillna("")
df

,CustomerID,Age,Gender,Tenure,MonthlyCharges,ContractType,InternetService,TotalCharges,TechSupport,Churn
0,1,49,Male,4,88.35,Month-to-Month,Fiber Optic,353.40,Yes,Yes
1,2,43,Male,0,36.67,Month-to-Month,Fiber Optic,0.00,Yes,Yes
2,3,51,Female,2,63.79,Month-to-Month,Fiber Optic,127.58,No,Yes
3,4,60,Female,8,102.34,One-Year,DSL,818.72,Yes,Yes
4,5,42,Male,32,69.01,Month-to-Month,,2208.32,No,Yes
...,...,...,...,...,...,...,...,...,...,...
995,996,42,Male,41,37.14,Month-to-Month,Fiber Optic,1522.74,Yes,Yes
996,997,62,Male,9,80.93,Month-to-Month,,728.37,No,Yes
997,998,51,Female,15,111.72,Month-to-Month,Fiber Optic,1675.80,Yes,Yes
998,999,39,Male,68,65.67,One-Year,,4465.56,No,Yes
999,1000,50,Male,1,56.67,Month-to-Month,,56.67,No,Yes

In [ ]:
# checking any missing values availble again
df.isnull().sum()

CustomerID         0
Age                0
Gender             0
Tenure             0
MonthlyCharges     0
ContractType       0
InternetService    0
TotalCharges       0
TechSupport        0
Churn              0
dtype: int64

In [ ]:
df.describe()

        CustomerID          Age      Tenure  MonthlyCharges  TotalCharges
count  1000.000000  1000.000000  1000.00000     1000.000000   1000.000000
mean    500.500000    44.674000    18.97300       74.391290   1404.364060
std     288.819436     9.797741    18.89257       25.712083   1571.755048
min       1.000000    12.000000     0.00000       30.000000      0.000000
25%     250.750000    38.000000     5.00000       52.357500    345.217500
50%     500.500000    45.000000    13.00000       74.060000    872.870000
75%     750.250000    51.000000    26.00000       96.102500   1900.175000
max    1000.000000    83.000000   122.00000      119.960000  12416.250000

In [ ]:
# Getting all numerical values in a single data to findout the relation between them
numeric=df.select_dtypes('number')
numeric

     CustomerID  Age  Tenure  MonthlyCharges  TotalCharges
0             1   49       4           88.35        353.40
1             2   43       0           36.67          0.00
2             3   51       2           63.79        127.58
3             4   60       8          102.34        818.72
4             5   42      32           69.01       2208.32
..          ...  ...     ...             ...           ...
995         996   42      41           37.14       1522.74
996         997   62       9           80.93        728.37
997         998   51      15          111.72       1675.80
998         999   39      68           65.67       4465.56
999        1000   50       1           56.67         56.67

[1000 rows x 5 columns]

In [ ]:
# findind correlation between the numerical values
numeric.corr()

                CustomerID       Age    Tenure  MonthlyCharges  TotalCharges
CustomerID        1.000000  0.036730 -0.018585       -0.030504     -0.027490
Age               0.036730  1.000000  0.000472        0.006362     -0.001896
Tenure           -0.018585  0.000472  1.000000       -0.014552      0.894868
MonthlyCharges   -0.030504  0.006362 -0.014552        1.000000      0.304893
TotalCharges     -0.027490 -0.001896  0.894868        0.304893      1.000000

In [ ]:
df

,CustomerID,Age,Gender,Tenure,MonthlyCharges,ContractType,InternetService,TotalCharges,TechSupport,Churn
0,1,49,Male,4,88.35,Month-to-Month,Fiber Optic,353.40,Yes,Yes
1,2,43,Male,0,36.67,Month-to-Month,Fiber Optic,0.00,Yes,Yes
2,3,51,Female,2,63.79,Month-to-Month,Fiber Optic,127.58,No,Yes
3,4,60,Female,8,102.34,One-Year,DSL,818.72,Yes,Yes
4,5,42,Male,32,69.01,Month-to-Month,,2208.32,No,Yes
...,...,...,...,...,...,...,...,...,...,...
995,996,42,Male,41,37.14,Month-to-Month,Fiber Optic,1522.74,Yes,Yes
996,997,62,Male,9,80.93,Month-to-Month,,728.37,No,Yes
997,998,51,Female,15,111.72,Month-to-Month,Fiber Optic,1675.80,Yes,Yes
998,999,39,Male,68,65.67,One-Year,,4465.56,No,Yes
999,1000,50,Male,1,56.67,Month-to-Month,,56.67,No,Yes

In [ ]:
df.groupby(['Churn','Gender'])["TotalCharges"].mean()

Churn  Gender
No     Female    1869.614706
       Male      1804.895918
Yes    Female    1290.246766
       Male      1410.107458
Name: TotalCharges, dtype: float64

In [ ]:
# Feature engineering
x=df[['Age','Gender','Tenure','MonthlyCharges']]
x
y=df.iloc[:,-1]
y

0      Yes
1      Yes
2      Yes
3      Yes
4      Yes
      ...
995    Yes
996    Yes
997    Yes
998    Yes
999    Yes
Name: Churn, Length: 1000, dtype: object

In [ ]:
#Feature scaling
x["Gender"]=x["Gender"].apply(lambda x:1 if x== "Male" else 0)
x

<ipython-input-33-72d7787ed584>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["Gender"]=x["Gender"].apply(lambda x:1 if x== "Male" else 0)

     Age  Gender  Tenure  MonthlyCharges
0     49       1       4           88.35
1     43       1       0           36.67
2     51       0       2           63.79
3     60       0       8          102.34
4     42       1      32           69.01
..   ...     ...     ...             ...
995   42       1      41           37.14
996   62       1       9           80.93
997   51       0      15          111.72
998   39       1      68           65.67
999   50       1       1           56.67

[1000 rows x 4 columns]

In [ ]:
y=y.apply(lambda x:1 if x=='Yes' else 0)
y

0      1
1      1
2      1
3      1
4      1
      ..
995    1
996    1
997    1
998    1
999    1
Name: Churn, Length: 1000, dtype: int64

In [ ]:
y.unique()

array([1, 0])

In [ ]:
type(y[0])

numpy.int64

In [120]:
# splitting the dataset
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [121]:
# Feature scaling for inputs for better accuracy
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(X_train)
x_train

array([[ 0.15565357, -0.91370804, -0.53629101,  0.91732938],
       [ 2.39563947, -0.91370804, -1.00223711, -1.47252139],
       [ 0.15565357,  1.0944415 , -1.00223711, -0.70252936],
       ...,
       [-0.55706922,  1.0944415 , -0.89869353, -0.00722017],
       [-0.04798152,  1.0944415 ,  0.39560118,  0.84104905],
       [ 1.37746406,  1.0944415 , -0.63983459,  0.92970996]])

In [122]:
x_test=scaler.fit_transform(X_test)

In [123]:
#Model creation
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
logistic=LogisticRegression()

In [124]:
# Model Training
logistic.fit(x_train,y_train)

LogisticRegression()

In [125]:
pred=logistic.predict(x_test)
pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [126]:
y_test

612    1
88     1
945    1
389    1
798    1
      ..
494    1
971    1
869    0
27     1
138    1
Name: Churn, Length: 200, dtype: int64

In [127]:
from sklearn.metrics import accuracy_score
accuracy_score(pred,y_test)*100

90.0

In [129]:
from  sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [132]:
y_pred1=rf.predict(x_test)

In [134]:
accuracy_score(y_pred1,y_test)

0.85

In [159]:
from sklearn.svm import SVC
svc=SVC(kernel='poly',C=0.29)

In [160]:
svc.fit(x_train,y_train)

SVC(C=0.29, kernel='poly')

In [161]:
pred2=svc.predict(x_test)
pred2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [162]:
accuracy_score(y_test,pred2)

0.9

In [165]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [166]:
pred3=dt.predict(x_test)
pred3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1])

In [167]:
accuracy_score(pred3,y_test)

0.815